### ISSUE TITLE
Re-align with CERN version

### ISSUE THREAD

**Issue by andreacalia** [ossgang/ossgang-spring-wonderland#1]
Ciao @kaifox,
we just realized a few days ago that we committed a few fixes on the CERN repo of wonderland :slightly_frowning_face: 
We'll have to align again at some point and keep this project alive here on Github.

In case you have any urgent feature to implement, we have to merge before doing it otherwise it'll be even more of a mess! Sorry for the inconvenience...

**Comment by kaifox** [comment]
Hi Guys,
no there is no urgent feature to implement. I think the only thing I did up to now, is configuring a travis build.... In principle I would say it should be easy to align as the gitub repo shoulde merely be a clone of the CERN one, right? I can easily wait before doing more, if you can find the time at some point to align the two ... If not, I can also have a look ...

**Comment by andreacalia** [comment]
Perfect @kaifox ! :slightly_smiling_face: 
I'll try to do it in the next weeks

**Comment by andreacalia** [comment]
Done.

* Version 0.2.0 has the latest code
* Version 0.3.0 has the new org.ossgang namespace
